# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[tableOfContents]
endLevel = 0
ordered = true
startLevel = 0

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
